name: osioki-jp

services:
  apache:
    build:
      context: ./app/apache
      dockerfile: Dockerfile
    volumes:
      # Config
      - ./app/apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      # Website roots
      - ./data/latest:/usr/local/apache2/htdocs/osioki.jp:ro
    environment:
      - TZ="Asia/Tokyo"
    networks:
      - docker-global

networks:
  docker-global:
    external: true
